### ISSUE TITLE
Video doesn't show in Safari

### ISSUE THREAD

**Issue by dracos** [BloombergMedia/whatiscode#10]
There's a gap, then the video appears behind the placeholder image. Looks like the responsive wrapper is being confused by the advert, it goes div.videoWrapper div.videoWrapper2 div.bvp-google-ads-container div div.video-js video, and the fourth div there is lacking a height:100% so the video has height 0, maybe? Plus double 56% top/bottom padding I think causing the gap? Not sure, sorry.

**Comment by tophtucker** [comment]
Should be better since https://github.com/BloombergMedia/whatiscode/commit/267ba8bbfb07bb54b46b43eaa37eeedff06ead65. We can reopen if not. Thanks @dracos!
