### ISSUE TITLE
Historical accuracy - 5.7 What About JavaScript plus what it actually did

### ISSUE THREAD

**Issue by putztzu** [BloombergMedia/whatiscode#101]
5.7 What About JavaScript

Quibbling about details,
Brendan Eich didn't exactly create a language and dub it "JavaScript." immediately.

He created a language originally named LiveScript, which after few versions embedded in the Netscape browser was re-named JavaScript (by Netscape or someone else? I don't remember. Contrary to the described "orphaned and non-sponsored" status of JavaScript I seem to remember it was fully adopted and supported by Netscape then. But that's purely based on my memory and would need to be researched. Of course, when Netscape fell in the MS vs Netscape war JavaScript's resources changed)

Many sources to support this history that it was originally LiveScript, one is Wikipedia "Timeline of programming languages"
https://en.wikipedia.org/wiki/Timeline_of_programming_languages

BTW - I became curious if today there exists anywhere a description of how JavaScript was used in those early days of HTML 2.0. And Google returned only one hit for me(Yes, actually written then although without specific date) I can find which is really cool... Note in the following link how "timers" were used to trigger scripts instead of today's methods that use User inputs and may be data driven. And, IIRC frames was a new invention which transformed how objects could be organized and placed on the page. IIRC in those days Livescript/JavaScript was only used to trigger tiny effects like transitions and backgrounds, little else.

http://www.angelfire.com/blog/javascript/js1/ch2.html

**Comment by bos1** [comment]
oh
