### ISSUE TITLE
There are 1318 (not 18) EWDs.

### ISSUE THREAD

**Issue by Christopher-Karl-Johansen** [BloombergMedia/whatiscode#105]
The sidebar in section 2.4 (What Is an Algorithm?) says,  " . . . set of 18 memos . . . ".  There are more than 1318 EWDs (https://www.cs.utexas.edu/~EWD/), some yet to be transcribed.  I suspect a tangled-finger typo in copy editing.

**Comment by tophtucker** [comment]
cf. #86
