### ISSUE TITLE
Unclear instruction in coding mini-tutorial

### ISSUE THREAD

**Issue by jonburge1** [BloombergMedia/whatiscode#123]
"Now get rid of pugs. The way you do that is by calling the pop method: dogs.pop();"

More clear would be "... dogs.pop('pugs')"

**Comment by tophtucker** [comment]
Javascript [`pop`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop) doesn't take any arguments, but you're right that it should be clarified what `pop` has to do with `pugs`, i.e. that `pop` returns the last element of an array and `pugs` is last.

**Comment by jonburge1** [comment]
Ah -- well I am clearly not familiar with Javascript. Thanks for the explanation!
