### ISSUE TITLE
LESS COWBELL --- I mean LESS COWBOY

### ISSUE THREAD

**Issue by TheSpiderPig** [BloombergMedia/whatiscode#13]
The cowboy stomping his food and coding is super annoying and distracting from reading.

**Comment by 1wheel** [comment]
That's a feature, not a bug! The bot's [standard library](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/#grabbag) replaces all the images with cowboys. 

You can always reload the page to get ride of them.

**Comment by tophtucker** [comment]
Or click "reset"
