### ISSUE TITLE
Missing reference at: Why are coders angry?

### ISSUE THREAD

**Issue by jcfausto** [BloombergMedia/whatiscode#135]
In the section: Why are coders angry?

In the 8th paragraph I´ve found this text: [insert 500-comment message thread here]. 

I think you forgot to actually insert the message link there.

Kind regards,

Julio.

**Comment by kingballer29** [comment]
I think this actually supposed to be a joke, as he writes: 
>They get defensive when they hear someone suggest that Python is better than Ruby, because [insert 500-comment message thread here]. 

So basically he is showing how  if someone suggests Python is better than Ruby, 500 comments will erupt in argument of why it is not or why it is by people, such as on YouTube and other places where people argue with each other in the comments.

**Comment by jcfausto** [comment]
I see. Thanks for the explanation. :-)
