### ISSUE TITLE
Windows 95 video is gone

### ISSUE THREAD

**Issue by jeffallen** [BloombergMedia/whatiscode#147]
In the "Briefly on the Huge Subject of Microsoft" section, the video is no longer available on YouTube.

Here is a replacement link: https://www.youtube.com/watch?v=b71rpN1iJKA

**Comment by YumekaMengjiaLYU** [comment]
The replacement link does not work for me. Is there another link for the video?

**Comment by jeffallen** [comment]
Maybe this one: https://www.youtube.com/watch?v=vLlWrt-zmTo
