### ISSUE TITLE
Link to gender breakdown data source

### ISSUE THREAD

**Issue by rebeccawilliams** [BloombergMedia/whatiscode#17]
This is a wonderful read. :heart: But despite all of these of other interactive features, there is no link to the data source for: 

![screen shot 2015-06-11 at 4 03 19 pm](https://cloud.githubusercontent.com/assets/1725454/8117002/32378670-1053-11e5-9683-d0797065aa09.png)

Can you cite and link to the data please?

**Comment by waldoj** [comment]
I am currently considering the possibility that I did not understand the thing that you wanted. That is, that you wanted a link to exist to the source of the data, and not that you wanted to be able to link to this graph as the source of data. :-/

**Comment by waldoj** [comment]
The data appears to come from [StackOverflow's 2015 Developer Survey](https://stackoverflow.com/research/developer-survey-2015).

**Comment by rebeccawilliams** [comment]
Ah, thanks! The data source was unclear when reading and I wanted that resolved for others with a link. The latter is also welcome though.

**Comment by waldoj** [comment]
Alright, I've included that in the pull request.

**Comment by rebeccawilliams** [comment]
:+1:

**Comment by 1wheel** [comment]
Thanks! Merging id for direct linking now. Getting github accounts for editors set up tomorrow so they can approve copy changes.

**Comment by derekeder** [comment]
Sorry, I'm about to throw a :wrench: in this thread ...

Adding a link to the source data would be awesome, but I'm not sure that a self-selected StackOverflow survey is a good source for this kind of info.

The 2013 American Community Survey has "Sex by Occupation for the Civilian Employed Population 16 Years and Over". For "Software developers and programmers" the total numbers are:

* male: 1,302,263
* female: 375,034

Which computes to 22% female 78% male

Source: http://censusreporter.org/data/table/?table=B24010&geo_ids=01000US&primary_geo_id=01000US

**Comment by 1wheel** [comment]
@derekeder We lost the caption from the magazine while (semi-manually) exporting to HTML:

![image](https://cloud.githubusercontent.com/assets/1643998/8141136/c6670be4-1130-11e5-9a4a-dee9c2b8f732.png)

Which (I think) does a pretty good job of indicating the charts are more of an observation about a particular group of programmers and less a statement of fact about all programers.

**Comment by knowtheory** [comment]
https://github.com/BloombergMedia/whatiscode/pull/18 was requested & merged re this issue.
