### ISSUE TITLE
Gcc on Mac is an alias for Clang

### ISSUE THREAD

**Issue by kdungs** [BloombergMedia/whatiscode#22]
Totally amazing read so far! Just a small thing that came to my mind:

In chapter 3.3 after the `squares.c` example it says

> That runs the GNU C Compiler 

which AFAIK is technically not true for a "normal" Mac. There `gcc` is an alias for `clang`.

**Comment by psiemens** [comment]
Can confirm.

![image](https://cloud.githubusercontent.com/assets/2547035/8121781/e0014d44-106d-11e5-9f00-e82a04f2592c.png)

**Comment by psiemens** [comment]
Can confirm.

![screen shot 2015-06-11 at 7 12 29 pm](https://cloud.githubusercontent.com/assets/2547035/8121845/5df1488a-106e-11e5-84e7-2eaa1e1f83f5.png)

**Comment by sushihangover** [comment]
I had the same basic question. 

Are you running a true gcc?
* With Xcode 4.2 or later, clang is the default and gcc is no longer included, just gcc --version 
* Or installed and compiled gcc yourself (or via Ports || Brew).
* Or using a Xcode (and/or cmd line tool install) and thus have a 'system' gcc which is really a symlink to * gcc-mavs and thus clang in disguise.

And the posting is great!!!. (FYI: I also love the whole using Github issues... :+1: )
