### ISSUE TITLE
Attribution for Fast Company Women in Tech piece

### ISSUE THREAD

**Issue by creatrixtiara** [BloombergMedia/whatiscode#38]
Referring to the paragraphs about women in code, specifically from Fast Company:

![screen shot 2015-06-12 at 6 21 54 pm](https://cloud.githubusercontent.com/assets/8474427/8142382/f0451d1c-112f-11e5-99e8-1892ea3dc632.png)

The writers of the article are Ciara Byrne and Jay Cassano. Given that Cassano is male I would imagine that those lines belong to Ciara Byrne.

**Comment by ftrain** [comment]
@tophtucker Not sure this is a copy?

**Comment by creatrixtiara** [comment]
Yeah, I saw the issue about Erica's attribution but didn't see one about Ciara's.

**Comment by tophtucker** [comment]
@ftrain @creatrixtiara Hi sorry I didn't mean "duplicate"! I have been using "copy" to label things related to article copy, as in "copy edit", i.e. text, to flag them for an editor to look at. But the word "copy" is overloaded and especially ambiguous in a GitHub context so I'll change to "text".

**Comment by creatrixtiara** [comment]
Oh whoops! I'm a writer, I should know that. Thanks for the clarification :)
