### ISSUE TITLE
PHP expansion is incorrect.

### ISSUE THREAD

**Issue by vaibhavsagar** [BloombergMedia/whatiscode#49]
According to the [wikipedia article](https://en.wikipedia.org/wiki/PHP), PHP was originally released as 'Personal Home Page Tools' and now stands for 'PHP: Hypertext Processor'.

**Comment by tophtucker** [comment]
cf. #6

**Comment by vaibhavsagar** [comment]
Didn't see that, thanks!

**Comment by tophtucker** [comment]
np! thanks for contributing
