### ISSUE TITLE
Text Hidden under the first video on iPad

### ISSUE THREAD

**Issue by Adzz** [BloombergMedia/whatiscode#55]
Text from: "In some mysterious way, he outranks you. Not within the company....." is hidden underneath the video above it when seen in chrome on an iPad.

**Comment by toyotabedzrock** [comment]
This also happens on the Nexus 10 with the Google Chrome Dev browser. The video is shifted down leaving a large white space and covering several paragraphs in landscape and portrait.

**Comment by tophtucker** [comment]
Finally fixed by https://github.com/BloombergMedia/whatiscode/commit/267ba8bbfb07bb54b46b43eaa37eeedff06ead65. Thanks y'all.
