### ISSUE TITLE
Translation of Paul Ford's article

### ISSUE THREAD

**Issue by gilvanvilarim** [BloombergMedia/whatiscode#58]
Hi. Is it possible do translate this article to other languages? There are texts and interactive content, but... If we could have access to the strings, it could be possible.

Best regards,
Gilvan.

**Comment by eshellman** [comment]
A translation of the text, other than a purely mechanical one, would be considered a derivative work, and is not permitted by the CC BY-ND-NC license. That is not to say that a translation could be permitted by the rights holder, presumably Bloomberg Media.

**Comment by 1wheel** [comment]
Duplicate of #28
