### ISSUE TITLE
Ad and huge blank space hide part of text

### ISSUE THREAD

**Issue by teo1978** [BloombergMedia/whatiscode#77]
http://postimg.org/image/3rf0rjk23/

**Comment by tophtucker** [comment]
Should finally be fixed by https://github.com/BloombergMedia/whatiscode/commit/267ba8bbfb07bb54b46b43eaa37eeedff06ead65, once deployed. Thanks @teo1978!

**Comment by tophtucker** [comment]
Although I guess we had some stopgap fix
