### ISSUE TITLE
Disneyland doesn't have wristbands

### ISSUE THREAD

**Issue by charlesdwesleyeplica** [BloombergMedia/whatiscode#85]
From the story: "Already you wander Disneyland with a wristband, and it watches and tracks you; the whole place is a computer."

But Disneyland doesn't have those wristbands, yet. Those wristbands are only available currently at Disney World.

(Loved the story)

**Comment by HipsterBrown** [comment]
Can confirm this. The MagicBand and FastPass+ system is only available at the Walt Disney World Resort properties at the moment 

https://disneyworld.disney.go.com/plan/my-disney-experience/bands-cards/

![screen shot 2015-06-16 at 10 58 05 am](https://cloud.githubusercontent.com/assets/3051193/8186157/98482728-1416-11e5-80c0-a0456efb5f0c.png)
