### ISSUE TITLE
Node JS year

### ISSUE THREAD

**Issue by randyburhan** [BloombergMedia/whatiscode#97]
"In 2008 a developer named Ryan Dahl modified the V8 engine"

Should it be 2009?
https://en.wikipedia.org/wiki/Node.js#cite_note-b1-20

**Comment by tophtucker** [comment]
Looks right. Here's the first commit: Feb 15, 2009 https://github.com/joyent/node/commit/9d7895c567e8f38abfff35da1b6d6d6a0a06f9aa

**Comment by ftrain** [comment]
:+1:
